/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fizzbuzzkata

import kotlin.test.Test
import kotlin.test.assertNotNull
import org.spekframework.spek2.Spek

object AppTest: Spek ({
	group( "normal" ) {
		test ("Given any input, when we ask whether it is Fizz or Buzz, then return Input") {
			assertNotNull("badinput")
		}
	}
})
