/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fizzbuzzkata

import kotlin.test.Test
import kotlin.test.assertNotNull
import org.spekframework.spek2.Spek
import org.spekframework.spek2.style.specification.describe
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.assertThrows

object AppTest: Spek ({
	group( "Top-Level Specs" ) {
		describe ("StringFor Input") {
			context("Given any input") {
				val input =1
				it("When I ask whether it is Fizz or Buzz, Then return Input as String") {
					val expected = "1"

					val actual = FizzBuzz.stringFor(input)

					assertEquals(expected, actual)
				}
			}

			context("Given input is integer less than 1") {
				val input = 0
				it("Throw IntegerLessThanOneException") {
					assertThrows<IntegerLessThanOneException> { FizzBuzz.stringFor(input) }
				}
			}
		}
	}
})
